### ISSUE TITLE
Problem pre compiling on mac Mojave due to Cairo (I think)

### ISSUE THREAD

**Issue by samdeetwo** [queryverse/Queryverse.jl#16]
Hello trying to use Queryverse, run into problem whent it is precompiling:

Below is the message I get from initial install of Queryverse. The problem is clearly first in Cairo. When I try to locally build Cairo, I get the following:
Get similar tasting error:
┌ Error: Error building Cairo:
│
│ signal (11): Segmentation fault: 11
│ in expression starting at /Users/sdanthine/.julia/packages/Cairo/CXPG1/deps/build.jl:165
│ _platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
│ Allocations: 19234553 (Pool: 19231774; Big: 2779); GC: 42

Funny thing is, managed to build it on one computer, not on the other. Both are Mac Mojave, both times initially Queryverse needed Cairo.

Error message when precompiling:

┌ Error: Error building Cairo, showing the last 100 of log:
│ See: https://docs.brew.sh/Homebrew-and-Python
│ ==> Summary
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/python/3.7.2_2: 3,861 files, 59.7MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/python/3.7.2_2
│ ==> Installing libffi from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/89b4ef328be250153e7a2b39982ac446e0b3bbfe7f3e2708912ba1976862c302--libffi-3.2.1.mojave.bottle.tar.gz
│ ==> Pouring libffi-3.2.1.mojave.bottle.tar.gz
│ ==> Caveats
│ libffi is keg-only, which means it was not symlinked into /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr,
│ because some formulae require a newer version of libffi.
│
│ For compilers to find libffi you may need to set:
│ export LDFLAGS="-L/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/libffi/lib"
│
│ For pkg-config to find libffi you may need to set:
│ export PKG_CONFIG_PATH="/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/libffi/lib/pkgconfig"
│
│ ==> Summary
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/libffi/3.2.1: 16 files, 297.0KB
│ ==> Installing glib from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/glib-2.60.0_1.mojave.bottle.tar.gz
│ ==> Pouring glib-2.60.0_1.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/glib/2.60.0_1: 432 files, 15.3MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/glib/2.60.0_1
│ ==> Installing libpng from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.36.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/b401f5b07a537975da7de448c4bbdaf0c2112d5dc7d8e0955e0d4fb938909010--libpng-1.6.36.mojave.bottle.tar.gz
│ ==> Pouring libpng-1.6.36.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/libpng/1.6.36: 27 files, 1.2MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/libpng/1.6.36
│ ==> Installing freetype from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/freetype-2.9.1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/89f20f0e2fae652cad0bf2c354912f65951b055050a0cf525f6a67939cb6e682--freetype-2.9.1.mojave.bottle.tar.gz
│ ==> Pouring freetype-2.9.1.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/freetype/2.9.1: 60 files, 2.6MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/freetype/2.9.1
│ ==> Installing fontconfig from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.13.1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/b7ad94d49bcdca22738f50b570efc07c7a20f98a469b3c4b32198b7318b8af5a--fontconfig-2.13.1.mojave.bottle.tar.gz
│ ==> Pouring fontconfig-2.13.1.mojave.bottle.tar.gz
│ ==> Regenerating font cache, this may take a while
│ ==> /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/fontconfig/2.13.1/bin/fc-cache -frv
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/fontconfig/2.13.1: 531 files, 3.3MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/fontconfig/2.13.1
│ ==> Installing pixman from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/pixman-0.38.0.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/0c26d4c3daf0b26cd91366caf1df3eca0bad5611e9742a0f8b409d6b80fc6a53--pixman-0.38.0.mojave.bottle.tar.gz
│ ==> Pouring pixman-0.38.0.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/pixman/0.38.0: 13 files, 1.3MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/pixman/0.38.0
│ ==> Installing cairo from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/cairo-1.16.0.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/fafc9fd181a939883ef055697994edea57d091a35299109bf774fc91092fbae7--cairo-1.16.0.mojave.bottle.tar.gz
│ ==> Pouring cairo-1.16.0.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/cairo/1.16.0: 117 files, 5.5MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/cairo/1.16.0
│ ==> Installing icu4c from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/icu4c-63.1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/88108185da55bf1af475d5e191e97f633514bd24c1c70bb89029af6cf5cc5185--icu4c-63.1.mojave.bottle.tar.gz
│ ==> Pouring icu4c-63.1.mojave.bottle.tar.gz
│ ==> Caveats
│ icu4c is keg-only, which means it was not symlinked into /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr,
│ because macOS provides libicucore.dylib (but nothing else).
│
│ If you need to have icu4c first in your PATH run:
│ echo 'export PATH="/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
│ echo 'export PATH="/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile
│
│ For compilers to find icu4c you may need to set:
│ export LDFLAGS="-L/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/icu4c/lib"
│ export CPPFLAGS="-I/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/icu4c/include"
│
│ For pkg-config to find icu4c you may need to set:
│ export PKG_CONFIG_PATH="/Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/opt/icu4c/lib/pkgconfig"
│
│ ==> Summary
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/icu4c/63.1: 254 files, 68.4MB
│ ==> Installing fribidi from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/fribidi-1.0.5.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/b966c6f589c81500014b64f8e15ff29e9b70f3e7ee8e0b0b5851f700c2ad0fa4--fribidi-1.0.5.mojave.bottle.tar.gz
│ ==> Pouring fribidi-1.0.5.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/fribidi/1.0.5: 66 files, 581.4KB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/fribidi/1.0.5
│ ==> Installing harfbuzz from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-2.3.1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/784a181552c10546bdab9595d963a36fa65d6e17cc04609285349cb81be623b9--harfbuzz-2.3.1.mojave.bottle.tar.gz
│ ==> Pouring harfbuzz-2.3.1.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/harfbuzz/2.3.1: 180 files, 9.5MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/harfbuzz/2.3.1
│ ==> Installing pango from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/pango-1.42.4_1.mojave.bottle.tar.gz
│ Already downloaded: /Users/sdanthine/Library/Caches/Homebrew.jl/downloads/f7d576fd30d48fab15ea38e97c79854a517864b3a64199be1550eb79e1143cf3--pango-1.42.4_1.mojave.bottle.tar.gz
│ ==> Pouring pango-1.42.4_1.mojave.bottle.tar.gz
│ 🍺 /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/pango/1.42.4_1: 106 files, 4.4MB
│ Warning: Already linked: /Users/sdanthine/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/pango/1.42.4_1
│
│ signal (11): Segmentation fault: 11
│ in expression starting at /Users/sdanthine/.julia/packages/Cairo/CXPG1/deps/build.jl:165
│ _platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
│ Allocations: 20858472 (Pool: 20855284; Big: 3188); GC: 46
│
│ Full log at /Users/sdanthine/.julia/packages/Cairo/CXPG1/deps/build.log

I have posted similar question on the Cairo git..
https://github.com/JuliaGraphics/Cairo.jl/issues/271

**Comment by davidanthoff** [comment]
Yeah, Cairo.jl unfortunately breaks pretty regularly... I think the only real long term solution is that someone finishes https://github.com/JuliaGraphics/Cairo.jl/pull/229... Which is a big job and not trivial at all.

**Comment by davidanthoff** [comment]
This should all work now.
