### ISSUE TITLE
@groupby and @map(_.key) issue

### ISSUE THREAD

**Issue by bhougland18** [queryverse/Queryverse.jl#18]
Hello,

I was working through your excellent video "Intro to the Queryverse" (https://youtu.be/OFPNph-WxLM?t=6050)) and didn't get the same output as you.  Your results were:

![image](https://user-images.githubusercontent.com/28444296/56704143-05ef8e00-66da-11e9-9de4-7adc04f10bfb.png)

When I run the code below I receive an error
`cars |> @groupby(_.Origin) |> @map(_.key)`
![image](https://user-images.githubusercontent.com/28444296/56704214-49e29300-66da-11e9-9e1b-1eca08c0dc3b.png)

**Comment by davidanthoff** [comment]
The syntax for this was changed when we moved to julia 1.0. Instead of `_.key` you now need to write `key(_)`. So `cars |> @groupby(_.Origin) |> @map(key(_))` should work.
