### ISSUE TITLE
Could not write `.dta` file

### ISSUE THREAD

**Issue by Okroshiashvili** [queryverse/Queryverse.jl#54]
I'm using `Queryverse` package to read SPSS, Stata, and SaS files but I can't write them back to the appropriate file format.
I'm getting the following error

```
No applicable_savers found for Stata

error(::String)@error.jl:33
applicable_savers@loadsave.jl:11[inlined]
#save#20(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(FileIO.save), ::String, ::DataFrames.DataFrame)@loadsave.jl:128
save@loadsave.jl:126[inlined]
top-level scope@Local: 1[inlined]
```

The writing functionality is not implemented yet, or there is a different reason why I could not write data say in Stata format?
I'm relatively new in Julia world

**Comment by davidanthoff** [comment]
Just not implemented yet. There are some PRs on ReadStat that would need to be finished and merged first.

**Comment by Okroshiashvili** [comment]
Thanks, @davidanthoff  for the quick replay. I'm relatively new in Julia's world and yet will not be able to help you with these PRs. Let me learn more and then I'd be happy to help you do these great things with this amazing language.

For now, closing the issue
