### ISSUE TITLE
loading package crashes whole Julia instance

### ISSUE THREAD

**Issue by sschelm** [queryverse/Queryverse.jl#8]
This behaviour happens with Julia 0.6.4 on Mac OS and Queryverse 0.0.2.

Calling `using Queyverse` crashes and exists the whole Julia REPL instance with the following error message: `ImportError: No module named site`

This behaviour is consistent on the CLI, Jupyter and Juno.

**Comment by sschelm** [comment]
The issue seems to come from the ExcelReaders package
```
julia> using ExcelReaders
INFO: Precompiling module ExcelReaders.
ImportError: No module named site
ERROR: Failed to precompile ExcelReaders to /Users/schelm/.julia/lib/v0.6/ExcelReaders.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
```

**Comment by davidanthoff** [comment]
Hm... Does the PyCall package generally work on your system?

**Comment by davidanthoff** [comment]
I think the issue is that you need the Python package xlrd installed. When you use a conda managed Python, that happens automatically, but with the system wide it probably doesn't. Could you try to install xlrd (via pip, I think) for the system wide Python and check whether that works?

**Comment by sschelm** [comment]
The xlrd package was not installed on the system wide versions, as you guessed.
I installed it for both python 2.7.15 and 3.6.6 and verified the installations.

Unfortunately it didn't really help:
For the 2.7.15 version, I'm getting an init error due to a segfault.
Whereas for the 3.6.6, I'm getting the original error:
```
ImportError: No module named site
ERROR: LoadError: LoadError: Failed to precompile ExcelReaders to /Users/schelm/.julia/lib/v0.6/ExcelReaders.ji.
```
Both during precompile of the ExcelReaders.ji package.

Is there another py module that's needed for ExcelReaders?

**Comment by sschelm** [comment]
Interesting.
When I check the packages in the Condo install with `./python pip freeze` at `~/.julia/v0.6/Conda/deps/usr/bin`, xlrd does not show up.

I'll have a look at the package diffs.

**Comment by sschelm** [comment]
I'm having huge troubles right now to get PyCall working with my system installs.
It therefore looks to me more like a setup and/or PyCall issue than a Queryverse or ExcelReader one.

I'm sticking to the Conda version for now.
